# scene
scene: stadium
is_interactive: false
build_graph: false
load_texture: true
pybullet_load_texture: true

# robot
robot: DexHandRobot
velocity: 1.0

# discount factor
discount_factor: 0.99

# termination condition
max_step: 1000

# sensor spec
output: [rgb, depth, seg, normal]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 640
image_height: 480
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false